name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - LICENSE
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: firmware-ci
